// Generated by binpac_quickstart

#include "plugin/Plugin.h"

#include "SFLOW.h"

namespace plugin {
namespace Bro_SFLOW {

class Plugin : public plugin::Plugin {
public:
	plugin::Configuration Configure()
		{
		AddComponent(new ::analyzer::Component("SFLOW",
		             ::analyzer::SFLOW::SFLOW_Analyzer::InstantiateAnalyzer));

		plugin::Configuration config;
		config.name = "Bro::SFLOW";
		config.description = "sFlow protocol analyzer";
                config.version.major = 1;
                config.version.minor = 0;
		return config;
		}
} plugin;

}
}
